### ISSUE TITLE
Build wheels for Python 3.11 and 3.12

### ISSUE THREAD

**Issue by IsakTheHacker** [emanuele-f/chaquopy-wheels#1]
As it currently stands, it is very hard to build the cryptography package with Chaquopy tools for Android. I have tried your instructions but I failed building the package on my own, so I just used one of your prebuilt wheels. If you have time over I would appreciate it if could build Cryptography for Python 3.11 and Python 3.12 since you already have everything setup correctly. Maybe also bump the package to the latest version while you're at it.

No problem if this isn't a priority, no stress at all, just think a lot of people benefit from your good work here! And lastly, thank you for bringing Cryptography 36.0.2 and newer to Chaquopy while the official support is still being worked on.

**Comment by emanuele-f** [comment]
Hi Isak, unfortunately this task requires a lot of time (I can tell this from my previous experience), and I have no plan to build them in the short term. My focus is to build mitmproxy for https://github.com/emanuele-f/PCAPdroid-mitm, and latest version still works with Python 3.10. I will keep this issue open

**Comment by IsakTheHacker** [comment]
Okay, that's unfortunate. If I succeed in building them myself I will keep
you updated. Thanks for the quick reply!

**Comment by emanuele-f** [comment]
If anyone is willing to sponsor this, please get in touch at black.silver@hotmail.it

**Comment by pay748** [comment]
I'd love to, but I don't have a credit card that supports international payments. I found on the GitHub sponsorship page that this is the only way to do it. Do you have palpay or alipay? Can you send the acceptance link or account to pay748@163.com? Thanks for your reply.

**Comment by emanuele-f** [comment]
Cryptography 42.0.8 wheels are [now available](https://github.com/chaquo/chaquopy/pull/1261) for Python 3.10 - 3.13 in the [official Chaquopy repo](https://chaquo.com/pypi-13.1/cryptography/)
